; METATILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : inicio Sheet
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 21
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : Yes.
;   Index offset         : 0
;   Index counter        : Tile-count as Constant.
;
; This file was generated by GBTD v2.2

 SECTION "inicio Sheet", ROM0

 MACRO ReordenaMetatiles
    ASSERT _NARG % 4 == 0
    REPT _NARG / 4
        DB \1, \3, \2, \4
        SHIFT 4
    ENDR
ENDM

; Metatile index
inicioSheetIndex::
    ReordenaMetatiles \
    $00,$01,$02,$03,$02,$03,$04,$05, \
    $01,$06,$03,$07,$08,$07,$09,$0A, \
    $0B,$0C,$0D,$03,$0E,$03,$0F,$10, \
    $11,$12,$03,$13,$01,$01,$03,$03, \
    $03,$03,$05,$05,$02,$03,$02,$03, \
    $03,$07,$03,$07,$03,$03,$03,$03, \
    $14,$15,$16,$17,$18,$19,$1A,$03, \
    $1B,$1C,$1D,$1E,$1F,$20,$21,$22, \
    $23,$24,$25,$26,$27,$28,$29,$2A, \
    $2B,$2C,$2D,$2E,$2F,$30,$03,$31, \
    $32,$33,$34,$03,$35,$35,$35,$35, \

; Start of tile array.
inicioSheet::
DB $00,$00,$7F,$7F,$7F,$7F,$7F,$7F
DB $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F
DB $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F
DB $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F
DB $00,$00,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$00,$FE,$FE,$FE,$FE,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F
DB $7F,$7F,$7F,$7F,$7F,$7F,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FE,$FF,$FC,$FB,$FE,$FF
DB $FE,$FE,$FE,$FE,$FE,$BE,$BE,$FE
DB $1E,$FE,$EE,$1E,$E6,$1A,$EE,$1E
DB $1E,$FE,$BE,$FE,$FE,$BE,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$00,$00
DB $FF,$F7,$F7,$FF,$E3,$FF,$DD,$E3
DB $9C,$63,$DD,$E3,$E3,$FF,$F7,$FF
DB $FF,$F7,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$7F,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FE,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$EF,$EF,$FF,$C7,$FF,$BB,$C7
DB $39,$C6,$BB,$C7,$C7,$FF,$EF,$FF
DB $FF,$EF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$F7
DB $F7,$FF,$E3,$FF,$DD,$E3,$9C,$63
DB $DD,$E3,$E3,$FF,$F7,$FF,$FF,$F7
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$E0,$FF,$EF,$DF,$AF,$DF
DB $EF,$9F,$AF,$DF,$EF,$DF,$E0,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$CF
DB $87,$FF,$E0,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$0F,$FF,$EF,$F7,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$0F,$FF
DB $E7,$FF,$E7,$FB,$E7,$FB,$E7,$FB
DB $E7,$FF,$0F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$F8,$FF,$F8,$FF,$F8,$FF
DB $F8,$FF,$F8,$FF,$F8,$FF,$F8,$FF
DB $F8,$FF,$F8,$FF,$F8,$FF,$F8,$FF
DB $F8,$FF,$FF,$F8,$FF,$FF,$FF,$FF
DB $FF,$FF,$0F,$F7,$F7,$0B,$F7,$09
DB $F7,$0B,$0F,$F7,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$F8,$F7,$F3,$EC
DB $E7,$DB,$C7,$FB,$C7,$FB,$C7,$FB
DB $C0,$FF,$C7,$F8,$C7,$FE,$C7,$FF
DB $C7,$FF,$C7,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$1F,$FF,$CF,$3F
DB $E7,$DF,$E3,$DF,$E3,$DF,$E3,$DF
DB $03,$FF,$E3,$1F,$E3,$7F,$E3,$FF
DB $E3,$FF,$E3,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FC,$FF,$E1,$FE,$EF,$F7
DB $EF,$DF,$EF,$DF,$EF,$9F,$EF,$9F
DB $EF,$9F,$EF,$9F,$EF,$DF,$EF,$D7
DB $E1,$FE,$F8,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$0F,$FF,$FF,$E1,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$E1,$07,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$C0,$FF,$C0,$FF
DB $EF,$D3,$EF,$D7,$EF,$D3,$E0,$DF
DB $E0,$DF,$EF,$D3,$EF,$D7,$EF,$D3
DB $C0,$FF,$C0,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$03,$FF,$07,$FB
DB $FF,$FF,$FF,$FF,$FF,$FF,$3F,$FF
DB $3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$FB,$03,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$E0,$FF,$FF,$F0
DB $C7,$F9,$C1,$FE,$C0,$FF,$C0,$FF
DB $C0,$FF,$C4,$FB,$C6,$FD,$C7,$FE
DB $C7,$FF,$C7,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$0F,$FF,$FF,$1F
DB $E3,$FF,$E3,$FF,$E3,$7F,$63,$BF
DB $23,$DF,$03,$FF,$03,$FF,$03,$FF
DB $83,$7F,$E3,$9F,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$CF,$F7,$EF,$DF
DB $EF,$DF,$EF,$DF,$EF,$DF,$EF,$DF
DB $EF,$DF,$EF,$DF,$EF,$DF,$EF,$D7
DB $E0,$FF,$E7,$D8,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$F3,$EF,$F7,$FB
DB $F7,$FB,$F7,$FB,$F7,$FB,$F7,$FB
DB $F7,$FB,$F7,$FB,$F7,$FB,$F7,$EB
DB $07,$FF,$F7,$0B,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$CF,$FF,$EF,$DF
DB $EF,$DF,$EF,$DF,$EF,$DF,$EF,$DF
DB $EF,$DF,$EF,$DF,$EF,$DF,$EF,$DF
DB $E0,$DF,$CF,$F0,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $03,$FF,$FB,$07,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FE,$FD,$FC,$FF
DB $FC,$FF,$FF,$FC,$FF,$FF,$C3,$FF
DB $DB,$E7,$DB,$E7,$C3,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$9F,$6F,$0F,$FF
DB $1F,$EF,$3F,$FF,$3F,$FF,$7F,$BF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

finInicioTiles::

; End of METATILES.Z80
