; INICIOMAPA.Z80
;
; Map Source File.
;
; Info:
;   Section       : Mapa Inicio
;   Bank          : 0
;   Map size      : 10 x 9
;   Tile set      : Z:\home\rhn4\Documentos\skypeia_d_ev_gb24\Tiles\inicioSheet.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8

 SECTION "Mapa Inicio", ROM0

MapaInit::
DB $00,$09,$09,$09,$09,$09,$09,$09,$09,$01
DB $07,$04,$0C,$0D,$0E,$0F,$10,$05,$0B,$08
DB $07,$0B,$0B,$04,$11,$05,$0B,$0B,$0B,$08
DB $07,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$08
DB $07,$04,$0D,$12,$13,$0C,$0E,$05,$0B,$08
DB $07,$0B,$0B,$04,$0E,$14,$05,$0B,$0B,$08
DB $07,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$08
DB $07,$04,$0B,$0B,$04,$05,$0B,$05,$0B,$08
DB $02,$0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A,$03

; End of INICIOMAPA.Z80
