; NAVE.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Nave", ROM0

; Start of tile array.
Nave::
DB $00,$00,$00,$01,$01,$01,$01,$01
DB $03,$03,$02,$03,$0A,$03,$0A,$03
DB $8F,$0C,$8E,$3F,$9E,$3F,$FE,$FF
DB $FF,$FF,$C3,$C3,$C1,$C1,$00,$C0
DB $00,$00,$00,$80,$80,$80,$80,$80
DB $C0,$C0,$40,$C0,$50,$C0,$51,$C0
DB $F1,$30,$71,$FC,$79,$FC,$7F,$FF
DB $FF,$FF,$C3,$C3,$83,$83,$00,$03
Nav_end::

Bullet::
DB $00,$00,$01,$01,$02,$03,$05,$06
DB $05,$06,$05,$06,$05,$06,$02,$03
DB $02,$03,$02,$03,$01,$01,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$80,$80,$40,$C0,$A0,$60
DB $A0,$60,$A0,$60,$A0,$60,$40,$C0
DB $40,$C0,$40,$C0,$80,$80,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
Bullet_end::


; End of NAVE.Z80
