; MAINCHARACTER.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROM0

inicioTiles::
; Start of tile array.
spriteJugador::
DB $03,$03,$07,$1F,$09,$0F,$0E,$0F
DB $1F,$19,$1F,$1A,$7F,$7A,$9F,$FC
DB $9B,$FF,$70,$7F,$FC,$8F,$F6,$97
DB $69,$6F,$11,$1F,$11,$1F,$0E,$0E
DB $C0,$C0,$E0,$F8,$90,$F0,$70,$F0
DB $F8,$B8,$F8,$58,$FE,$5E,$F9,$3F
DB $D9,$FF,$0E,$FE,$3F,$F1,$6F,$E9
DB $96,$F6,$88,$F8,$88,$F8,$70,$70
finSpriteJugador::

enemySprite::
DB $03,$03,$07,$1F,$09,$0F,$0E,$0F
DB $1F,$19,$1F,$1A,$7F,$7A,$9F,$FC
DB $9B,$FF,$70,$7F,$FC,$8F,$F6,$97
DB $69,$6F,$11,$1F,$11,$1F,$0E,$0E
DB $C0,$C0,$E0,$F8,$90,$F0,$70,$F0
DB $F8,$B8,$F8,$58,$FE,$5E,$F9,$3F
DB $D9,$FF,$0E,$FE,$3F,$F1,$6F,$E9
DB $96,$F6,$88,$F8,$88,$F8,$70,$70
finSpriteEnemy::

finTiles::

