; VICTORYMAP.Z80
;
; Map Source File.
;
; Info:
;   Section       : Victory Map
;   Bank          : 0
;   Map size      : 10 x 9
;   Tile set      : Z:\home\rhn4\Documentos\skypeia_d_ev_gb24\Tiles\DEFINITIVEsheet.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8


 SECTION "Victory Map", ROM0

VIctoryMap::
DB $00,$09,$09,$09,$09,$09,$09,$09,$09,$01
DB $07,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$08
DB $07,$0B,$04,$04,$04,$04,$04,$04,$0B,$08
DB $07,$04,$0B,$0B,$0B,$0B,$0B,$0B,$04,$08
DB $07,$15,$16,$0F,$17,$18,$19,$1A,$14,$08
DB $07,$06,$0B,$0B,$0B,$0B,$0B,$0B,$06,$08
DB $07,$0B,$04,$04,$04,$04,$04,$04,$0B,$08
DB $07,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$0B,$08
DB $02,$0A,$0A,$0A,$0A,$0A,$0A,$0A,$0A,$03

; End of VICTORYMAP.Z80
